#!/usr/bin/env bash
# Shows information about subdomains.

the_domain_info() {
    line=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$2 $line" | awk '{printf "The subdomain " $1 " is a " $2 " record and points to " $3\n}'
}

if [ "$#" == 1 ]
then
    the_domain_info "$1" "www"
    the_domain_info "$1" "lb-01"
    the_domain_info "$1" "web-01"
    the_domain_info "$1" "web-02"
elif [ "$#" == 2 ]
then
    the_domain_info "$1" "$2"
fi
