#!/usr/bin/env bash
# Configure your domain zone so that the subdomain www points to your
#load-balancer IP (lb-01). Let’s also add other subdomains to make our
#life easier, and write a Bash script that will display information about subdomains.

the_domain_info() {
     dig "$1" | grep -A1 'ANSWER SECTION:' |
	     sed -r "s/$1./$2/g" | awk -F" " ' NR==2 { print "The subdomain " $1 " is a " $4 " record and points to " $5 }'
}

if [ "$#" -eq 1 ]; then
    the_domain_info "$1" "www"
    the_domain_info "$1" "lb-01"
    the_domain_info "$1" "web-01"
    the_domain_info "$1" "web-02"
elif [ "$#" -eq 2 ]; then
    domain_information "$1" "$2"
fi
