#!/usr/bin/env bash
#Write a Bash script that transfers a file from our client to a server

if [ $# -lt 4 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

# Now assigning the variable to their parametals

PATH_TO_FILE=$1
IP=$2
USERNAME=$3
PATH_TO_SSH_KEY=$4


scp -o "StrictHostKeyChecking=no" -i "$PATH_TO_SSH_KEY" "$PATH_TO_FILE" "$USERNAME@Sip:~/"

if [ $? -eq 0 ]
then
	echo "The file was tansfered (**SUCCESSFULLY**)"
else
	echo "The file was tansfered (!!UNSUCCESSFULLY!!)"
fi
