#!/usr/bin/env bash
# diong a 301 prermanent move

sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World" | sudo tee /var/www/html/index.html

replacement_string="server_name _;\n\trewrite ^\/redirecting_me https:\/\/github.com\/Steven\-Awo permanent;"

sudo sed -i "s/server_name _;/$replacement_string/" /etc/nginx/sites-enabled/default

sudo service nginx restart
