#!/usr/bin/env bash
# costomiz the 404 page a 301 prermanent move

sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World" | sudo tee /var/www/html/index.html

replacement_string="server_name _;\n\trewrite ^\/redirecting_me https:\/\/github.com\/Steven\-Awo permanent;"

sudo sed -i "s/server_name _;/$replacement_string/" /etc/nginx/sites-enabled/default

#404 file

echo "Ceci n'est pas une page" | sudo tee /var/www/html/d_404.html

string_for_replacement="listen 80 default_server;\n\terror_page 404 /d_404.html;\n\tlocation = /d_404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}"

sudo sed -i "s/listen 80 default_server;/$string_for_replacement/" /etc/nginx/sites-enabled/default

sudo service nginx restart
