#!/usr/bin/env bash
# Setting up haproxxy

# Installing and configuring HAproxy on the lb-01 server.

sudo apt-get -y update

apt-get -y install haproxy

# editing the config file

server_config=\
"
frontend rotimi_frontend
        bind *:80
        mode http
        default_backend rotimi_backend
backend rotimi_backend
        balance roundrobin
        server 427691-web-01 52.91.137.7:80 check
        server 427691-web-02 100.25.33.74:80 check
"

echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo haproxy -c -f /etc/haproxy/haproxy.cfg

sudo service haproxy restart
