#!/usr/bin/env bash
# Just the same as in task 0 but by adding -f to the ln to just
# forcefully remove all the file(s) if they exists

ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

sudo service nginx restart

sudo nginx -t

rm /run/nginx.pid

sudo nginx -t
