#!/usr/bin/env bash
# forcefully remove all the file(s) if they exists
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
sudo nginx -t
rm /run/nginx.pid
service nginx restart
