#!/usr/bin/env bash
# displays all the contents that are in the file `/etc/passwd`.
# displays only the user id, username, and the user home's directory path.

while read -r passwd; do
  echo "$passwrd" | cut -d ':' -f1,3,6
done < "/etc/passwd"
