#!/usr/bin/env bash
# Displays numbers from 1 to 20 in addition to:
# displays the message "bad luck from China" on the 4th iteration
# displays the message "bad luck from Japan" on the 9th iteration
# displays the message "bad luck from Italy" on the 17th iteration

counts=1

while [ $counts -le 20 ]
do
  echo "$counts"
  case $counts in
    "4") echo "bad luck from China";;
    "9") echo "bad luck from Japan";;
    "17") echo "bad luck from Italy";;
  esac
  (( counts++ ))
done
